CREATE TABLE OXA_ADAPTER_INT
   (	OXA_ID VARCHAR(255) NOT NULL, 
	MESSAGE_ID VARCHAR(255) NOT NULL, 
	SENDER_ID VARCHAR(255) NOT NULL, 
	RECEIVER_ID VARCHAR(255) NOT NULL, 
	DOCUMENT_TYPE VARCHAR(255) NOT NULL, 
	RECEIVED_TIMESTAMP TIMESTAMP NOT NULL, 
	PROCESSED VARCHAR(1) DEFAULT 'N' NOT NULL
   );

CREATE TABLE OXA_ADAPTER_LOG
   (id integer auto_increment primary key, 
	LOG_TYPE VARCHAR(255) NOT NULL, 
	LOG_OPERATION VARCHAR(255), 
	LOG_DESCRIPTION VARCHAR(2000), 
	LOG_VALUE VARCHAR(255), 
	LOG_LARGE_VALUE MEDIUMTEXT, 
	LOG_URL_CONTEXT VARCHAR(255), 
	LOG_CORRELATION_ID VARCHAR(255), 
	LOG_DOCUMENT_ID VARCHAR(255), 
	LOG_DOCUMENT_TYPE_CD VARCHAR(255), 
	LOG_BUS_CORRELATION_ID VARCHAR(255), 
	LOG_TRA_ID INTEGER, 
	LOG_MSG_ID INTEGER, 
	LOG_MSG_BIN_ID INTEGER, 
	LOG_ISSUER_PTY_ID INTEGER, 
	LOG_SENDER_PTY_ID INTEGER, 
	LOG_RECEIVER_PTY_ID INTEGER, 
	LOG_BUSINESS_DOMAIN INTEGER, 
	CRE_DT TIMESTAMP, 
	CRE_ID VARCHAR(255), 
	MOD_DT TIMESTAMP, 
	MOD_ID VARCHAR(255), 
	LOG_MSG_SIZE INTEGER, 
	LOG_MODULE VARCHAR(255), 
	LOG_USRNAME VARCHAR(255), 
	LOG_USR_ROLE VARCHAR(255), 
	LOG_AUTH_IP_ADDRESS VARCHAR(255), 
	LOG_ENTITY VARCHAR(255), 
	LOG_ENITITY_ID INTEGER, 
	LOG_CLASS VARCHAR(255) 
   );

CREATE TRIGGER OXA_TG_MESSAGE_INSERT AFTER INSERT ON oxa_messages 
FOR EACH ROW
  INSERT INTO OXA_ADAPTER_INT  (OXA_ID, MESSAGE_ID, SENDER_ID, RECEIVER_ID, DOCUMENT_TYPE, RECEIVED_TIMESTAMP)
   VALUES (NEW.ID, NEW.MESSAGEID, NEW.SENDERID, NEW.RECIPIENTID, NEW.DOCUMENTTYPEIDENTIFIER, NEW.RECEIVEDTIMESTAMP);

CREATE TABLE OXA_ADAPTER_METADATA (MD_TYPE VARCHAR(255) NOT NULL, MD_VALUE LONGTEXT NOT NULL);

